config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }, :controllers => { :registrations => "users/registrations" }

  resources :reports
  resources :users

  root 'home#index'

end

app/models/ability.rb
class Ability
 
  include CanCan::Ability 

  def initialize (user) 
    
    user ||= User.new(:role_id => 1)

    if user.admin?
      can :manage, :all 
    else
      can :manage, Report do |report| 
        report.try (:owner) == user
      end 
    end 

  end 

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :width, :height, :cost, :comment
  validates :width, numericality: { only_integer: true }
  validates :height, numericality: { only_integer: true }
  validates :cost, numericality: true
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users 
end

app/models/user.rb
class User < ActiveRecord::Base
  
  before_create :set_default_role
  
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable
  
  belongs_to :role
  has_many :reports, :dependent => :destroy
  
  def admin?
  	self.role.name == 'admin'
  end 

  def set_default_role
  	self.role = Role.find_by_name('user') if self.role_id.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from CanCan::AccessDenied do | exception | 
    flash[:error] = exception.message 
    redirect_to root_url
  end
  
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  before_action :authenticate_user!
  
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin?
      @q = Report.search(params[:q])
      @reports = @q.result(distinct: true)
    else
      @q = current_user.reports.search(params[:q])
      @reports = @q.result(distinct: true)
    end
  end

  def show
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user
    if @report.save
      redirect_to @report, notice: 'Report was successfully created.'
    else
      render :new
    end
  end

  def update
      if @report.update(report_params)
        redirect_to @report, notice: 'Report was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    if @report.destroy
      redirect_to reports_url, notice: 'Report was successfully destroyed.'
    end
  end

  private
    def set_report
      @report = Report.find(params[:id])
    end
    def report_params
      params.require(:report).permit(:width, :height, :cost, :comment)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController 
  skip_before_filter :require_no_authentication 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  load_and_authorize_resource except: :create
  
  before_action :authenticate_user!
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    if @user.destroy
      redirect_to reports_url, notice: 'User was successfully destroyed.'
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:email, :password, :role_id, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.jumbotron
  - unless user_signed_in?
    %h1 Welcome to our Awesome App!
    %p.lead Before you start using it, please sign up.
    %p
      = link_to 'Login', new_user_session_path, class: 'btn btn-lg btn-success'
      or
      = link_to 'Sign up', new_user_registration_path
  - else
    %h2 Hi, user!
    Your role is:
    %strong= current_user.role.name
    %br
    So, you can 
    = link_to reports_path do
      manage reports
    - if can? :manage, User
      and
      = link_to users_path do
        manage users

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Reporting Test Application
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .header
        = render 'shared/nav'
        %h3.text-muted
          = link_to root_url do
            Reporting Test App
      - flash.each do |key, value|
        %div{:class => "alert flash #{key}"}
          = value
      = yield
      .footer
        %p
          © Reporting Test App by Aleksandr Ponomarenko 2014
          - if user_signed_in?
            %span.pull-right
              = current_user.email
              (#{current_user.role.name})

app/views/reports/_form.html.haml
= form_for @report, :html => { :class => 'form-horizontal' } do |f|
  - if @report.errors.any?
    %ul
      - @report.errors.each do |key, value|
        %li 
          %strong
            = key.to_s.titleize
          = value
  .control-group
    = f.label :width, :class => 'control-label'
    .controls
      = f.text_field :width, :class => 'text_field'
  .control-group
    = f.label :height, :class => 'control-label'
    .controls
      = f.text_field :height, :class => 'text_field'
  .control-group
    = f.label :cost, :class => 'control-label'
    .controls
      = f.text_field :cost, :class => 'text_field'
  .control-group
    = f.label :comment, :class => 'control-label'
    .controls
      = f.text_area :comment, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), reports_path, :class => 'btn'

app/views/reports/edit.html.haml
.page-header
  %h1 Edit report
= render :partial => "form"

app/views/reports/index.html.haml
.page-header
  %h1 Reports

  = search_form_for @q, :class => 'form-horizontal'  do |f|
    = f.label :width_eq
    = f.search_field :width_eq
    = f.label :height_eq
    = f.search_field :height_eq
    = f.label :cost_eq
    = f.search_field :cost_eq
    = f.label :comment_cont
    = f.search_field :comment_cont
    = f.submit
%table.table.table-striped
  %thead
    %tr
      %th id
      %th width
      %th height
      %th cost
      %th comment
      %th Owner
      %th Created at
      %th Actions
  %tbody
    - @reports.each do |report|
      %tr
        %td= link_to report.id, report_path(report)
        %td= report.width
        %td= report.height
        %td= report.cost
        %td= report.comment
        %td= report.user.email
        %td= l report.created_at, format: :long
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(report), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(report), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_report_path, :class => 'btn btn-primary'

app/views/reports/new.html.haml
.page-header
  %h1 New report
= render :partial => "form"

app/views/reports/show.html.haml
.page-header
  %h1 Report

%p
  %strong width:
  = @report.width
%p
  %strong height:
  = @report.height
%p
  %strong cost
  = @report.cost
%p
  %strong comment
  = @report.comment
%p
  %strong user
  = @report.user.email

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), reports_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(@report), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(@report), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/shared/_nav.html.haml
%ul.nav.nav-pills.pull-right
  - unless user_signed_in?
    %li
      = link_to new_user_registration_path do
        %i.icon-user
        Sign Up
    %li
      = link_to new_user_session_path do
        %i.icon-signin
        Sign In
  - else
    %li{:class => ('active' if controller_name == 'reports' )}
      = link_to reports_path do
        Reports
    - if can? :manage, User
      %li{:class => ('active' if controller_name == 'users' )}
        = link_to users_path do
          Users
    %li
      = link_to destroy_user_session_path, method: 'delete' do
        %i.icon-signout
        Sign Out

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal' } do |f|
  - if @user.errors.any?
    %ul
      - @user.errors.each do |key, value|
        %li 
          %strong
            = key.to_s.titleize
          = value
  .control-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  - unless @user.persisted?
    .control-group
      = f.label :password, :class => 'control-label'
      .controls
        = f.text_field :password, :class => 'text_field'
        (leave blank if you don't want to change it)
  .control-group
    = f.label :role, :class => 'control-label'
    .controls
      = f.collection_select :role_id, Role.all, :id, :name
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.haml
.page-header
  %h1 Edit user
= render :partial => "form"

app/views/users/index.html.haml
.page-header
  %h1 Users
%table.table.table-striped
  %thead
    %tr
      %th id
      %th email
      %th Created at
      %th Reports total
      %th Actions
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.email
        %td= l user.created_at, format: :long
        %td= user.reports.count
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
.page-header
  %h1 New user
= render :partial => "form"

app/views/users/show.html.haml
.page-header
  %h1 User

%p
  %strong Email:
  = @user.email
%p
  %strong Role:
  = @user.role.name
%p
  %strong Created at
  = l @user.created_at, format: :long

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'